# Generated by Django 5.2.5 on 2025-09-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0003_alter_facility_options'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('nature_of_project', models.CharField(choices=[('RESEARCH', 'Research'), ('PROTOTYPE', 'Prototype'), ('APPLIED_WORK', 'Applied Work')], max_length=50)),
                ('description', models.TextField()),
                ('innovation_focus', models.CharField(choices=[('IOT_DEVICES', 'IoT devices'), ('SMART_HOME', 'Smart home'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('AI_SOLUTIONS', 'AI solutions'), ('ROBOTICS', 'Robotics')], max_length=50)),
                ('prototype_stage', models.CharField(choices=[('CONCEPT', 'Concept'), ('PROTOTYPE', 'Prototype'), ('MVP', 'Minimum Viable Product (MVP)'), ('MARKET_LAUNCH', 'Market Launch')], max_length=50)),
                ('testing_requirements', models.TextField(blank=True)),
                ('commercialization_plan', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='facilities.facility')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='programs.program')),
            ],
        ),
    ]
