# Generated by Django 5.2.5 on 2025-09-02 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_project', models.CharField(choices=[('STUDENT', 'Student'), ('LECTURER', 'Lecturer'), ('CONTRIBUTOR', 'Contributor'), ('MENTOR', 'Mentor')], default='STUDENT', max_length=20)),
                ('skill_role', models.CharField(choices=[('DEVELOPER', 'Developer'), ('ENGINEER', 'Engineer'), ('DESIGNER', 'Designer'), ('BUSINESS_LEAD', 'Business Lead'), ('RESEARCHER', 'Researcher'), ('TESTER', 'Tester')], default='DEVELOPER', max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectParticipant', to='participants.participant'),
        ),
    ]
