# Generated by Django 5.2.5 on 2025-09-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_created_at_alter_facility_facility_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
    ]
