# Generated by Django 5.2.5 on 2025-09-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('facilities', '0003_alter_facility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='capabilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='facility',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='support_phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usage_domain',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
