# Generated by Django 5.2.5 on 2025-09-02 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_options'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility'),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
