# Generated by Django 5.2.5 on 2025-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('ENG', 'Engineering'), ('OTHER', 'Other')], max_length=10)),
                ('specialization', models.CharField(choices=[('SOFTWARE', 'Software'), ('HARDWARE', 'Hardware'), ('BUSINESS', 'Business')], max_length=20)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(choices=[('SCIT', 'SCIT'), ('CEDAT', 'CEDAT'), ('UNIPOD', 'UniPod'), ('UIRI', 'UIRI'), ('LWERA', 'Lwera')], max_length=20)),
            ],
        ),
    ]
