# Generated by Django 5.2.5 on 2025-09-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectparticipant_project_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('artifact_link', models.URLField(blank=True, null=True)),
                ('artifact_file', models.FileField(blank=True, null=True, upload_to='outcomes/')),
                ('outcome_type', models.CharField(choices=[('CAD', 'CAD Design'), ('PCB', 'PCB Design'), ('PROTOTYPE', 'Prototype'), ('REPORT', 'Report'), ('BUSINESS_PLAN', 'Business Plan'), ('SOFTWARE', 'Software'), ('DOCUMENTATION', 'Documentation')], max_length=20)),
                ('quality_certification', models.TextField(blank=True, null=True)),
                ('commercialization_status', models.CharField(choices=[('DEFINED', 'Defined'), ('MARKET_LINKED', 'Market Linked'), ('LAUNCHED', 'Launched')], default='DEFINED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
