# Generated by Django 5.2.5 on 2025-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('national_alignment', models.CharField(help_text='Link to NDPIII, Roadmap, or 4IR goals', max_length=300)),
                ('focus_areas', models.CharField(choices=[('IOT', 'IoT'), ('AUTOMATION', 'Automation'), ('RENEWABLE_ENERGY', 'Renewable Energy'), ('AI_ML', 'AI/ML'), ('ROBOTICS', 'Robotics')], max_length=100)),
                ('phases', models.CharField(choices=[('CROSS_SKILLING', 'Cross-Skilling'), ('COLLABORATION', 'Collaboration'), ('TECHNICAL_SKILLS', 'Technical Skills'), ('PROTOTYPING', 'Prototyping'), ('COMMERCIALIZATION', 'Commercialization')], max_length=100)),
            ],
        ),
    ]
